name: Run Pytest Tests

on:
  schedule:
    # Run at 1:00 AM every day
    - cron: "0 1 * * *"

  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3" # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py 
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --html=report.html --self-contained-html --css=pytest-html-report.css # Generates report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html
